theme: jekyll-theme-cayman
title: Hello, I'm Akash.
description: I am a Computer Science undergrad at IIT Tirupati. Algorithms, deep learning and recently enough parallel programming and distributed systems fascinate me.
